/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mypkg;

import org.junit.Test;
import static org.junit.Assert.*;

public class DriverTest {
    @Test public void testDriverHasAGreeting() {
        Driver classUnderTest = new Driver();
        assertNotNull("Driver should have a greeting.", classUnderTest.getGreeting());
    }
}