/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mypkg;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;

import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.RealMatrix;

public class Driver {
    private static final Logger logger = LogManager.getLogger();
    
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Configurator.setLevel(logger.getName(), Level.ALL);
        logger.info("Starting program.");
        doMatrixStuff(); // set up matrixes
        logger.info("Exiting program.");
    }

    private static void doMatrixStuff() {
        double[][] m1_data = new double[][] {
            new double[]{1d, 5d},
            new double[]{2d, 3d},
            new double[]{1d, 7d}
        };

        double[][] m2_data = new double[][] {
            new double[]{1d, 5d},
            new double[]{2d, 3d},
        };

        RealMatrix m1 = new Array2DRowRealMatrix(m1_data);
        RealMatrix m2 = new Array2DRowRealMatrix(m2_data);

        RealMatrix r1 = Wahoovian.wahoovian(m1);
        RealMatrix r2 = Wahoovian.wahoovian(m2);

        System.out.println();
        System.out.println("Matrix product before: " + m1);
        System.out.println("Matrix product after: " + r1);
        System.out.println();
        System.out.println("Matrix product before: " + m2);
        System.out.println("Matrix product after: " + r2);
        System.out.println();
    }

    public static Logger getLogger() {
        return logger;
    }
}